### ISSUE TITLE
Is there a any way to host upsell out of UltraCart Server?

### ISSUE THREAD

**Issue by vijaykc** [UltraCart/two_page_trial#6]
Hello,

Can we host/use external page for upsell with yes/no button?

Any idea?

Thanks,
Vijay

**Comment by perrytew** [comment]
To do so, you'll need to create a custom javascript checkout using the REST API.  This two page trial project is an example of that.  When using the javascript checkout, instead of call /rest/cart/checkout, you'll call /rest/cart/validate first, and the /rest/cart/finalizeAfter.  The latter call sets a timer that will automatically process the order after a set time limit.  This is done in case the customer abandons the web site during the upsell.

After that, you can proceed to present your upsell page with additional product offerings.  If the customer wishes to add to the cart, simply add the items and call /rest/cart/ (PUT) as normal to update the cart.  If the customer continues through the upsell, at the end, just call /rest/cart/checkout as normal.  If they abandon, the finalizeAfter timer will catch the order and process it.

**Comment by perrytew** [comment]
Closing.  Please reopen if needed.
